mpich2-1.2.1rc1

diff --git a/mpich2/maint/updatefiles b/mpich2/maint/updatefiles
--- a/mpich2/maint/updatefiles
+++ b/mpich2/maint/updatefiles
@@ -38,6 +38,13 @@ do_smpdversion=yes
 # Allow MAKE to be set from the environment
 MAKE=${MAKE-make}
 
+# ltdirs are the directories that make use of libtool and 
+# require libtoolize 
+# externals are the directories for external packages that we have 
+# included into MPICH2
+externals="src/pm/hydra/tools/bind/hwloc/hwloc"
+ltdirs="src/pm/hydra"
+# amdirs are the directories that make use of autoreconf
 amdirs="src/openpa src/pm/hydra src/mpl"
 
 # List of steps that we will consider
@@ -45,21 +52,12 @@ amdirs="src/openpa src/pm/hydra src/mpl"
 AllSteps="geterrmsgs bindings f77 f77tof90 build_configure genstates makefiles smpdversion getparms"
 stepsCleared=no
 
-# Options for some steps
-autoconfdir=""
-automakedir=""
-autotoolsdir=""
 # Extract defaults from the environment
-if [ "x$MPICH2_AUTOCONF_DIR" != "x" ] ; then 
-    autoconfdir=$MPICH2_AUTOCONF_DIR
-fi
-if [ "x$MPICH2_AUTOMAKE_DIR" != "x" ] ; then 
-    automakedir=$MPICH2_AUTOMAKE_DIR
-fi
-if [ "x$MPICH2_AUTOTOOLS_DIR" != "x" ] ; then 
-    autotoolsdir=$MPICH2_AUTOTOOLS_DIR
-fi
-#
+autoconfdir=$MPICH2_AUTOCONF_DIR
+automakedir=$MPICH2_AUTOMAKE_DIR
+libtooldir=$MPICH2_LIBTOOL_DIR
+autotoolsdir=$MPICH2_AUTOTOOLS_DIR
+
 # Extract the arguments intended for updatefiles.  Any others are
 # given to simplemake.  
 temp_args=""
@@ -130,6 +128,9 @@ for arg in "$@" ; do
     -with-automake=*|--with-automake=*)
     automakedir=`echo "A$arg" | sed -e 's/.*=//'`
     ;;
+    -with-libtool=*|--with-libtool=*)
+    libtooldir=`echo "A$arg" | sed -e 's/.*=//'`
+    ;;
     -with-autotools=*|--with-autotools=*)
     autotoolsdir=`echo "A$arg" | sed -e 's/.*=//'`
     ;;
@@ -143,17 +144,18 @@ for arg in "$@" ; do
     -help|--help|-usage|--usage)
     cat <<EOF
     updatefiles [ --with-autoconf=dir ] [ --with-automake=dir ] \\
-                [ --with-autotools=dir ] [ --do=stepname ]       \\
-                [ args for simplemake ] 
+                [ --with-libtool=dir ] [ --with-autotools=dir ] \\
+                [ --do=stepname ] [ args for simplemake ]
     Update the files in the MPICH2 build tree.  This file builds the 
     configure files, creates the Makefile.in files (using the simplemake
     program), extracts the error messages.
 
-    You can use --with-autoconf=dir to specify a directory that contains
-    an alternate autoconf and autoheader.  Similarly --with-automake can
-    be used to specify the location of automake and aclocal.  If
-    autoconf and automake are installed in the same location, they can
-    be specified by the --with-autotools option.
+    You can use --with-autoconf=dir to specify a directory that
+    contains an alternate autoconf and autoheader.  Similarly
+    --with-automake can be used to specify the location of automake
+    and aclocal and --with-libtool to specify the location of
+    libtoolize. If all the autotools are installed in the same
+    location, they can be specified by the --with-autotools option.
 
     Use --do=stepname to update only a single step.  For example, 
     --do=build_configure only updates the configure scripts.  The available
@@ -172,22 +174,24 @@ EOF
 done
 
 if [ -n "$autotoolsdir" ] ; then
-    if [ -n "$autoconfdir" -o -n "$automakedir" ] ; then
-        # Don't permit --with-autotools together with either --with-autoconf or
-        # --with-automake because which argument takes precedence is not obvious
-        # without immediate explanation.  --with-autotools is really only
-        # present to make life a little easier for those who preferred the old
-        # behavior where --with-autoconf was used to specify the location of
-        # both autoconf and automake.
+    if [ -n "$autoconfdir" -o -n "$automakedir" -o -n "$libtooldir" ] ; then
+        # Don't permit --with-autotools together with --with-autoconf,
+        # --with-automake or --with-libtool because which argument
+        # takes precedence is not obvious without immediate
+        # explanation.  --with-autotools is really only present to
+        # make life a little easier for those who preferred the old
+        # behavior where --with-autoconf was used to specify the
+        # location of both autoconf and automake.
         cat <<EOT
-Error: --with-autotools was specified together with either
---with-autoconf or --with-automake.  --with-autotools is incompatible
-with the other two options.  Please specify only one set or the other.
+Error: --with-autotools was specified together with --with-autoconf,
+--with-automake or --with-libtool.  --with-autotools is incompatible
+with the other options.  Please specify only one set or the other.
 EOT
         exit 1
     else
         autoconfdir=$autotoolsdir
         automakedir=$autotoolsdir
+	libtooldir=$autotoolsdir
     fi
 fi
 
@@ -269,6 +273,18 @@ else
     automake=${AUTOMAKE:-automake}
     aclocal=${ACLOCAL:-aclocal}
 fi
+if [ -n "$libtooldir" ] ; then
+    if [ -x "$libtooldir/libtoolize" ] ; then
+        libtoolize=$libtooldir/libtoolize
+        LIBTOOLIZE=$libtoolize
+        export LIBTOOLIZE
+    else
+        echo "could not find executable libtoolize in $libtooldir"
+        exit 1
+    fi
+else
+    libtoolize=${LIBTOOLIZE:-libtoolize}
+fi
 
 #
 # Check that you have a working autoconf.  Autoconf 2.57 is not compatible with
@@ -289,7 +305,9 @@ fi
 # -1 is used for unknown
 acSubversion=-1
 acIncDirFlag=-I
-for ver in 64 63 62 61 60 59 ; do
+# Try to keep at least one version ahead of autoconf (e.g., if current is
+# 2.64, include a test for 2.65)
+for ver in 65 64 63 62 61 60 59 ; do
     rm -f .tmp/configure.in .tmp/configure
     cat >.tmp/configure.in <<EOF
 AC_PREREQ(2.$ver)
@@ -863,10 +881,25 @@ fi
 if [ "$do_build_configure" = "yes" -o "$do_makefiles" = "yes" ] ; then
     # must come after the above autoreconf-like logic because the above
     # logic will delete the results of this actual autoreconf
+
+    for external in $externals ; do
+       if [ -d "$external" -o -L "$external" ] ; then
+           echo "running third-party initialization"
+           (cd $external && ./autogen.sh) || exit 1
+       fi
+    done
+
+    for ltdir in $ltdirs ; do
+	if [ -d "$ltdir" -o -L "$ltdir" ] ; then
+	    echo "running $libtoolize in $ltdir"
+	    (cd $ltdir && $libtoolize) || exit 1
+	fi
+    done
+
     for amdir in $amdirs ; do
 	if [ -d "$amdir" -o -L "$amdir" ] ; then
-	    echo "running autoreconf in $amdir"
-	    (cd $amdir && autoreconf -vif) || exit 1
+	    echo "running $autoreconf in $amdir"
+	    (cd $amdir && $autoreconf -vif) || exit 1
 	fi
     done
 fi
@@ -880,7 +913,7 @@ if [ $rm_prepost = yes ] ; then
 fi
 if [ "$do_smpdversion" = yes ] ; then
     echo "Creating src/pm/smpd/smpd_version.h"
-    smpdVersion=`cat maint/Version`
+    smpdVersion=`cat maint/Version | grep ^MPICH2_VERSION | cut -f2 -d' '`
     cat >src/pm/smpd/smpd_version.h <<EOF
 /* -*- Mode: C; c-basic-offset:4 ; -*- */
 /*  
@@ -891,7 +924,7 @@ if [ "$do_smpdversion" = yes ] ; then
 EOF
 fi
 
-VERSION=`cat maint/Version`
+VERSION=`cat maint/Version | grep ^MPICH2_VERSION | cut -f2 -d' '`
 if [ -f README.vin ] ; then
     echo "Updating README's version ID."
     sed -e "s/%VERSION%/${VERSION}/g" README.vin > README
@@ -899,18 +932,6 @@ else
     echo "README.vin file not present, unable to update README version number (perhaps we are running in a release tarball source tree?)"
 fi
 
-fedora_spec=src/packaging/spec/fedora.spec
-if [ -f ${fedora_spec}.vin ] ; then
-    echo "Updating fedora spec file's version numbers"
-    BASIC_VERSION=`expr $VERSION : '\([0-9]*\.[0-9]*[\.]*[0-9]*\)[a-zA-Z]*[0-9]*'`
-    VERSION_EXT=`expr $VERSION : '[0-9]*\.[0-9]*[\.]*[0-9]*\([a-zA-Z]*[0-9]*\)'`
-    sed -e "s/%BASIC_VERSION%/${BASIC_VERSION}/g" -e "s/%VERSION_EXT%/${VERSION_EXT}/g" \
-        ${fedora_spec}.vin > ${fedora_spec}
-else
-    echo "fedora.spec.vin not present, unable to update fedora.spec version numbers"
-fi
-
-#
 # The following must be the last statements executed
 if [ -n "$error_summary" ] ; then
     echo " "
