mpich2-1.2

diff --git a/mpich2/maint/updatefiles b/mpich2/maint/updatefiles
--- a/mpich2/maint/updatefiles
+++ b/mpich2/maint/updatefiles
@@ -38,8 +38,7 @@ do_smpdversion=yes
 # Allow MAKE to be set from the environment
 MAKE=${MAKE-make}
 
-openpa_dir="src/openpa"
-hydra_dir="src/pm/hydra"
+amdirs="src/openpa src/pm/hydra src/mpl"
 
 # List of steps that we will consider
 # (We do not include depend because the values for depend are not just yes/no)
@@ -70,8 +69,8 @@ for arg in "$@" ; do
 	set -x
 	;;
 	
-    -do=*)
-    opt=`echo A$arg | sed -e 's/A-do=//'`
+    -do=*|--do=*)
+    opt=`echo A$arg | sed -e 's/^A--*do=//'`
     # Handle some synonyms
     case $opt in 
 	build-configure|configure) opt=build_configure ;;
@@ -144,7 +143,7 @@ for arg in "$@" ; do
     -help|--help|-usage|--usage)
     cat <<EOF
     updatefiles [ --with-autoconf=dir ] [ --with-automake=dir ] \\
-                [ --with-autotools=dir ] [ -do=stepname ]       \\
+                [ --with-autotools=dir ] [ --do=stepname ]       \\
                 [ args for simplemake ] 
     Update the files in the MPICH2 build tree.  This file builds the 
     configure files, creates the Makefile.in files (using the simplemake
@@ -156,11 +155,14 @@ for arg in "$@" ; do
     autoconf and automake are installed in the same location, they can
     be specified by the --with-autotools option.
 
-    Use -do=stepname to update only a single step.  For example, 
-    -do=build_configure only updates the configure scripts.  The available
-    steps are
-    $AllSteps
+    Use --do=stepname to update only a single step.  For example, 
+    --do=build_configure only updates the configure scripts.  The available
+    steps are:
 EOF
+    for step in $AllSteps
+    do
+       echo "        $step"
+    done
     exit
     ;;
     *)
@@ -301,9 +303,10 @@ rm -f .tmp/configure.in .tmp/configure
 if [ "$acSubversion" -gt 0 ] ; then
     acVersion="2.$acSubversion"
     echo "You have autoconf version $acVersion or greater."
-    if [ "$acSubversion" -lt 62 ] ; then 
+    # this used to be a check for >=63, but we only work with exactly 2.63 right now
+    if [ "$acSubversion" -ne 63 ] ; then
        cat <<EOF
-autoconf version 2.62 or later is required for MPICH2.
+autoconf version 2.63 (exactly) is required
 EOF
        if [ "$do_build_configure" = yes ] ; then 
             echo "Exiting updatefiles...."
@@ -637,23 +640,20 @@ if [ $do_build_configure = yes ] ; then
 	        # be used instead of this one when building that configure
 	        continue
             fi
-	    qhydra=`echo $dir | sed -e 's%.*'"$hydra_dir"'.*%FOUNDHYDRA%'`
-	    if [ "$qhydra" = "FOUNDHYDRA" ] ; then
-	        # hydra is updated using autoreconf later in this script
-	        continue
-            fi
-	    qopenpa=`echo $dir | sed -e 's%.*'"$openpa_dir"'.*%FOUNDOPENPA%'`
-	    if [ "$qopenpa" = "FOUNDOPENPA" ] ; then
-	        # openpa is updated using autoreconf later in this script
-	        continue
-            fi
-            qopenpa=`echo $dir | sed -e 's%.*openpa.*%FOUNDOPENPA%'`
-            if [ "$qopenpa" = "FOUNDOPENPA" ] ; then
-                # this is the old openpa location (in the root of the package)
-                # this clause exists because SVN won't delete the old directory
-                # when you run "svn update".
-                continue
-            fi
+
+	    found=0
+	    for amdir in $amdirs ; do
+		foo=`echo $dir | sed -e 's%.*'"$amdir"'.*%FOUNDFOO%'`
+		if [ "$foo" = "FOUNDFOO" ] ; then
+		    # We'll use autoreconf later in this script for these directories
+		    found=1
+		    break
+		fi
+	    done
+	    if [ "$found" = "1" ] ; then
+		continue
+	    fi
+
 	    if [ -s $dir/Makefile.in ] ; then 
                 #echo "Found $dir/configure.in"
 	        #
@@ -698,6 +698,10 @@ if [ $do_build_configure = yes ] ; then
 	        if grep 'configure:' $dir/Makefile.in >/dev/null 2>&1 ; then
  	            # The make -q checks whether the target is upto date first;
 	            # if it isn't, we remake it.
+		    # The make target should be for ${srcdir}/configure,
+		    # so in the make line, the target needs to be ./configure
+		    # Using just "configure" is incorrect and will fail with
+		    # some makes.
 		    rm -f $dir/mf.out 
 		    rm -f $dir/mf.newer
 		    date > $dir/mf.newer
@@ -706,10 +710,10 @@ if [ $do_build_configure = yes ] ; then
 		        -e "s%@srcdir@%.%g" \
 		        -e '/include .*alldeps/d' \
 		        -e '/@SET_MAKE@/d' Makefile.in > mf.tmp ;\
-		        if ${MAKE} -q -f mf.tmp configure >mf.out 2>&1 ; then \
+		        if ${MAKE} -q -f mf.tmp ./configure >mf.out 2>&1 ; then \
                     : ; else \
 	            echo "Found $dir/configure.in; executing make configure target" ; \
-	            ${MAKE} -f mf.tmp configure ; fi ; \
+	            ${MAKE} -f mf.tmp ./configure ; fi ; \
 			if [ -s configure ] ; then rm -f mf.tmp ; \
 			else echo "See `pwd`/mf.tmp for Makefile that failed" ;\
                         fi ;\
@@ -856,15 +860,15 @@ if [ $do_build_configure = yes ] ; then
     fi
 fi
 
-# must come after the above autoreconf-like logic because the above
-# logic will delete the results of this actual autoreconf
-if [ -d "$openpa_dir" -o -L "$openpa_dir" ] ; then
-    echo "running autoreconf in $openpa_dir"
-    (cd $openpa_dir && $autoreconf -vif) || exit 1
-fi
-if [ -d "$hydra_dir" -o -L "$hydra_dir" ] ; then
-    echo "running autoreconf in $hydra_dir"
-    (cd $hydra_dir && $autoreconf -vif) || exit 1
+if [ "$do_build_configure" = "yes" -o "$do_makefiles" = "yes" ] ; then
+    # must come after the above autoreconf-like logic because the above
+    # logic will delete the results of this actual autoreconf
+    for amdir in $amdirs ; do
+	if [ -d "$amdir" -o -L "$amdir" ] ; then
+	    echo "running autoreconf in $amdir"
+	    (cd $amdir && autoreconf -vif) || exit 1
+	fi
+    done
 fi
 
 if [ -f src/mpe2/maint/updatefiles -a "$do_build_configure" = "yes" ] ; then
@@ -887,14 +891,24 @@ if [ "$do_smpdversion" = yes ] ; then
 EOF
 fi
 
-echo "Updating README's version ID."
 VERSION=`cat maint/Version`
-sed -e "s/%VERSION%/${VERSION}/g" README.vin > README
+if [ -f README.vin ] ; then
+    echo "Updating README's version ID."
+    sed -e "s/%VERSION%/${VERSION}/g" README.vin > README
+else
+    echo "README.vin file not present, unable to update README version number (perhaps we are running in a release tarball source tree?)"
+fi
 
-BASIC_VERSION=`expr $VERSION : '\([0-9]*\.[0-9]*[\.]*[0-9]*\)[a-zA-Z]*[0-9]*'`
-VERSION_EXT=`expr $VERSION : '[0-9]*\.[0-9]*[\.]*[0-9]*\([a-zA-Z]*[0-9]*\)'`
-sed -e "s/%BASIC_VERSION%/${BASIC_VERSION}/g" -e "s/%VERSION_EXT%/${VERSION_EXT}/g" \
-    src/packaging/spec/fedora.spec.vin > src/packaging/spec/fedora.spec
+fedora_spec=src/packaging/spec/fedora.spec
+if [ -f ${fedora_spec}.vin ] ; then
+    echo "Updating fedora spec file's version numbers"
+    BASIC_VERSION=`expr $VERSION : '\([0-9]*\.[0-9]*[\.]*[0-9]*\)[a-zA-Z]*[0-9]*'`
+    VERSION_EXT=`expr $VERSION : '[0-9]*\.[0-9]*[\.]*[0-9]*\([a-zA-Z]*[0-9]*\)'`
+    sed -e "s/%BASIC_VERSION%/${BASIC_VERSION}/g" -e "s/%VERSION_EXT%/${VERSION_EXT}/g" \
+        ${fedora_spec}.vin > ${fedora_spec}
+else
+    echo "fedora.spec.vin not present, unable to update fedora.spec version numbers"
+fi
 
 #
 # The following must be the last statements executed
